name: cinematic_insights
description: A Movie App.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.13


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  color: "#000000"




flutter:


  uses-material-design: true

  assets:
   - assets/

 
