// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCepuWgCT5Gwz7hTxuBcvEenKEwymoUTgw',
    appId: '1:445356305682:web:f38d35491ee692e9fa17cb',
    messagingSenderId: '445356305682',
    projectId: 'cinematic-insights',
    authDomain: 'cinematic-insights.firebaseapp.com',
    storageBucket: 'cinematic-insights.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lQ5nzA7vSJSDFZ_e6mZ4g-cL2Uc-pB0',
    appId: '1:445356305682:android:4cb57b8ae37c1c03fa17cb',
    messagingSenderId: '445356305682',
    projectId: 'cinematic-insights',
    storageBucket: 'cinematic-insights.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiF4r_As5rg4Kd6IVu0Toy-SI4SXk-M-o',
    appId: '1:445356305682:ios:234211e7299754a5fa17cb',
    messagingSenderId: '445356305682',
    projectId: 'cinematic-insights',
    storageBucket: 'cinematic-insights.appspot.com',
    iosBundleId: 'com.example.g21097716MovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiF4r_As5rg4Kd6IVu0Toy-SI4SXk-M-o',
    appId: '1:445356305682:ios:f84be33a657d3df3fa17cb',
    messagingSenderId: '445356305682',
    projectId: 'cinematic-insights',
    storageBucket: 'cinematic-insights.appspot.com',
    iosBundleId: 'com.example.g21097716MovieApp.RunnerTests',
  );
}
